cluster_name = "local-cluster"
location = "local-2"
server_id = 2 # the server to connect to
local_deployment = true # use localhost
summary_filepath = "../benchmarks/logs/local-run/client-2.json"
output_filepath = "../benchmarks/logs/local-run/client-2.csv"

# Defining TOML vector of (duration_sec, requests_per_sec, read_ratio) which determines the behavior of the client requests
[[requests]]
duration_sec = 2
requests_per_sec = 10
read_ratio = 0

[[requests]]
duration_sec = 2
requests_per_sec = 11
read_ratio = 0

[[requests]]
duration_sec = 2
requests_per_sec = 12
read_ratio = 0

[[requests]]
duration_sec = 2
requests_per_sec = 13
read_ratio = 0

[[requests]]
duration_sec = 1
requests_per_sec = 19
read_ratio = 0

[[requests]]
duration_sec = 1
requests_per_sec = 24
read_ratio = 0

[[requests]]
duration_sec = 1
requests_per_sec = 32
read_ratio = 0

[[requests]]
duration_sec = 1
requests_per_sec = 36
read_ratio = 0

[[requests]]
duration_sec = 2
requests_per_sec = 38
read_ratio = 0