location = "local-5"
server_id = 5 # the server to connect to
server_address = "127.0.0.1:8005"
summary_filepath = "./logs/client-5.json"
output_filepath = "./logs/client-5.csv"

# Defining TOML vector of (duration_sec, requests_per_sec, read_ratio) which determines the behavior of the client requests
[[requests]]
duration_sec = 5
requests_per_sec = 10
read_ratio = 0

[[requests]]
duration_sec = 45
requests_per_sec = 100
read_ratio = 0

[[disconnect_node_requests]]
trigger_sec = 20