location = "local-1"
server_id = 1 # the server to connect to
server_address = "127.0.0.1:8001"
summary_filepath = "./logs/client-1.json"
output_filepath = "./logs/client-1.csv"

# Defining TOML vector of (duration_sec, requests_per_sec, read_ratio) which determines the behavior of the client requests
[[requests]]
duration_sec = 5
requests_per_sec = 200
read_ratio = 0

[[requests]]
duration_sec = 15
requests_per_sec = 1000
read_ratio = 0

[[disconnect_nodes_requests]]
trigger_sec = 10
nodes = [5]

[[disconnect_nodes_requests]]
trigger_sec = 15
nodes = [4]

[[kill_links_requests]]
trigger_sec = 20
links = [[2,3]]