location = "local-3"
server_id = 3 # the server to connect to
server_address = "127.0.0.1:8003"
summary_filepath = "./logs/client-3.json"
output_filepath = "./logs/client-3.csv"

# Defining TOML vector of (duration_sec, requests_per_sec, read_ratio) which determines the behavior of the client requests
[[requests]]
duration_sec = 5
requests_per_sec = 10
read_ratio = 0

[[requests]]
duration_sec = 45
requests_per_sec = 1000
read_ratio = 0

[[kill_links_requests]]
trigger_sec = 30
links = [4,2]

[[kill_links_requests]]
trigger_sec = 10
links = [1]

[[connect_links_requests]]
trigger_sec = 40
links = [2]
