location = "local-5"
server_id = 5
num_clients = 1 # Hardcoded number of client connections to wait for
listen_address = "127.0.0.1"
listen_port = 8005
output_filepath = "./logs/server-5.json"
#size_buffer_data_ids = 100